M48
; DRILL file {KiCad (6.0.10)} date Mon Jan 30 13:49:29 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-01-30T13:49:29-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.800
%
G90
G05
T1
X85.674Y-55.58
X93.65Y-55.58
T2
X118.225Y-56.5
X123.075Y-56.5
T3
X117.925Y-53.47
X123.375Y-53.47
T0
M30
